### ISSUE TITLE
Collector not pushing to Prometheus

### ISSUE THREAD

**Issue by nitin02** [slok/ecs-exporter#2]
I'm trying the ecs-exporter with the latest version of Prometheus.

I get an error at, collector.go:129. What can be the source of this issue?

Below is a stack trace I get in the log. Some aws specific information is replaced with xxxx.

`
time="2017-06-21T07:15:11Z" level=error msg="Tried to send a metric after collection context has finished, metric: &{%!s(*prometheus.Desc=&{ecs_container_instance_agent_connected The connected state of the container instance agent [] [region cluster instance] _xxxx_ _xxxx_<nil>}) %!s(prometheus.ValueType=2) %!s(float64=1) [%!s(*io_prometheus_client.LabelPair=&{0xc420ab91f0 0xc420ab9200 []}) %!s(*io_prometheus_client.LabelPair=&{0xc420ab9210 0xc420ab9220 []}) %!s(*io_prometheus_client.LabelPair=&{0xc420ab91d0 0xc420ab91e0 []})]}" source="collector.go:129"`

This error happens for every metric. 

I can find the metrics created in Prometheus, but with no data.

Also, I've been searching for use of **flags**  (command line docker arguments) with ECS Task definition. Does it have this feature? If not, what is a workaround for setting the configuration.

**Comment by nitin02** [comment]
I can see the metrics data being populated now in Prometheus, but still the above error (similar for other metrics too) persists in the log.

Also, I find,
_Error collecting cluster service metrics: ThrottlingException: Rate exceeded
Error collecting cluster container instance metrics: ThrottlingException: Rate exceeded_

Is there a way to reduce polling frequency?

**Comment by slok** [comment]
The frequency of polling is the frecuency of the Prometheus request, so you will need to change the frequency on the Prometheus endpoint `evaluation_interval`.

The error that you are seeing... my guess (I don't know exactly) is that the ecs exporter is returning the metrics to prometheus, but there are so many metrics (or AWS API is taking too much time to return the metrics to the exporter) that Prometheus closes the connection (`scrape_timeout`) before the ecs exporter finishes returning all the metrics to Prometheus, that's why you see some of the metrics on Prometheus.

**Comment by nitin02** [comment]
Hello,

Thanks for the reply. Will check the suggestions.

Also, for setting docker flags with AWS ECS. Is there a way or a workaround?

**Comment by slok** [comment]
Checkout `command` in [task definition documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)

**Comment by slok** [comment]
I seems that @nitin02 manage to get it working. Closing the issue
